# Generated by Django 4.0.3 on 2022-03-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_visit', models.CharField(max_length=20, verbose_name='Event')),
                ('time', models.DateField(verbose_name='Appointment date')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Doctor visit',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=20, verbose_name='Medicine name')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('serving', models.TextField(blank=True, verbose_name='Serving')),
            ],
            options={
                'verbose_name': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='News_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Time')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=20, verbose_name='Symptom')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Symptom',
            },
        ),
        migrations.CreateModel(
            name='Take_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_out', models.CharField(max_length=20, verbose_name='Take out food')),
                ('start_time', models.DateTimeField(verbose_name='Time')),
                ('restaurant', models.CharField(max_length=50, verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Take out food',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20, verbose_name='Place')),
                ('start_time', models.DateField(verbose_name='Start date')),
                ('end_time', models.DateField(verbose_name='End date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trip',
            },
        ),
        migrations.AlterModelOptions(
            name='demoforeignkey',
            options={'verbose_name': '全部字段非必填', 'verbose_name_plural': '全部字段非必填'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile'},
        ),
        migrations.AlterField(
            model_name='demoforeignkey',
            name='bool',
            field=models.BooleanField(blank=True, verbose_name='BooleanField'),
        ),
        migrations.AlterField(
            model_name='demoforeignkey',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='FileField'),
        ),
        migrations.AlterField(
            model_name='demoforeignkey',
            name='float_number',
            field=models.FloatField(blank=True, verbose_name='FloatField'),
        ),
        migrations.AlterField(
            model_name='demoforeignkey',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='ImageField'),
        ),
        migrations.AlterField(
            model_name='demoforeignkey',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='CharField列'),
        ),
        migrations.AlterField(
            model_name='demoforeignkey',
            name='text',
            field=models.TextField(blank=True, verbose_name='TextField'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'male')], default='female', max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Profile Photo'),
        ),
    ]
