# Generated by Django 4.0.3 on 2022-04-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_doctor_visit_medicine_news_info_symptom_take_out_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoDefaultModel',
        ),
        migrations.RemoveField(
            model_name='demomodel',
            name='foreign_key_field',
        ),
        migrations.DeleteModel(
            name='DemoModelRequire',
        ),
        migrations.RemoveField(
            model_name='richtextdemo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='richtextdemo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='richtextdemo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DemoForeignKey',
        ),
        migrations.DeleteModel(
            name='DemoModel',
        ),
        migrations.DeleteModel(
            name='RichTextDemo',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
